In [30]:
import os
import yfinance as yf

# Make sure the data directories exist
os.makedirs("../data/raw", exist_ok=True)
os.makedirs("../data/processed", exist_ok=True)

In [31]:
# 2. Download 3 years of history
tickers = ["AAPL", "GOOGL", "TSLA"]
start = "2022-07-01"
end   = "2025-07-01"

raw = {}
for t in tickers:
    df = yf.download(t, start=start, end=end)
    df = df.drop(df.index[1])
    # now this will succeed
    df.to_csv(f"../data/raw/{t}.csv")
    raw[t] = df
df

/var/folders/jq/mbgbv6211m9816f1py7zsb0c0000gn/T/ipykernel_87335/3561057797.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(t, start=start, end=end)
[*********************100%***********************]  1 of 1 completed
/var/folders/jq/mbgbv6211m9816f1py7zsb0c0000gn/T/ipykernel_87335/3561057797.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(t, start=start, end=end)
[*********************100%***********************]  1 of 1 completed
/var/folders/jq/mbgbv6211m9816f1py7zsb0c0000gn/T/ipykernel_87335/3561057797.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(t, start=start, end=end)
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            TSLA        TSLA        TSLA        TSLA       TSLA
Date
2022-07-01  227.263336  230.229996  222.119995  227.000000   74460300
2022-07-06  231.733337  234.563339  227.186661  230.779999   71853600
2022-07-07  244.543335  245.363327  232.210007  233.919998   81930600
2022-07-08  250.763336  254.979996  241.160004  242.333328  101854200
2022-07-11  234.343338  253.063339  233.626663  252.103333   99241200
...                ...         ...         ...         ...        ...
2025-06-24  340.470001  356.260010  340.440002  356.170013  114736200
2025-06-25  327.549988  343.000000  320.399994  342.700012  119845100
2025-06-26  325.779999  331.049988  323.609985  324.609985   80440900
2025-06-27  323.630005  329.339996  317.500000  324.510010   89067000
2025-06-30  317.660004  325.579987  316.600006  319.899994   76695100

[750 rows x 5 columns]

In [29]:
import pandas as pd
import glob

for path in glob.glob("../data/raw/*.csv"):
    # read in, skip only line 2 (0‑based index = 1)
    df = pd.read_csv(path, skiprows=[1])
    # overwrite the file without that ticker row
    df.to_csv(path, index=False)